server:
  port: 8000

spring:
  application:
    name: gateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  security:
    user:
      name: user
      password: 1234

  profiles:
    include:
      - cloud
      - eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh