spring:
  cloud:
    gateway:
  #      default-filters:
  #        - name: GlobalFilter
  #          args:
  #            baseMessage: Spring Cloud GateWay Filter
  #            preLogger: true
  #            postLogger: true

  #      routes:
  #        - id: member-service
  #          uri: lb://member-service
  #          predicates:
  #            - Path=/member-service/register
  #            - Method=POST
  #          filters:
  #            - RemoveRequestHeader=Cookie
  #            - RewritePath=/member-service/(?<segment>.*), /$\{segment}