### 1. 회원가입 oauth2

POST {{naver}}
Content-Type: application/json
Accept: */*
Connection: keep-alive

> {%
    client.test("소셜 로그인 회원 가입 성공, 토큰 클라이언트 저장", function() {
        client.assert(response.status === 200, "Response status is OK");
        client.global.set("accessToken", response.body.accessToken);
        client.global.set("refreshToken", response.body.refreshToken);
        client.global.set("refreshToken", response.body.userId);
        client.log(client.global.get("accessToken"));
        client.log(client.global.get("refreshToken"));
        client.log(client.global.get("userId"));
    });
%}