### 1. waitRoom 검색

GET {{baseUrl}}/waitroom/search
Content-Type: application/json
Accept: */*
Connection: keep-alive
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNTliNDljZC03OGQyLTRiMmQtOGFhMi01Yjk4NmI2MjMyNTEiLCJhdXRoIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNjc1NDIzNDc1LCJleHAiOjE2NzU0NDUwNzV9.H9mLnrDz2qtRkw3eZdUrFaZZJvMIbaqxmFkXh8Z3sYT6cVUXglaO0AUIw-JHSxiyBa6mhJDtJh_wnmiW-HAkfA
RefreshToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNTliNDljZC03OGQyLTRiMmQtOGFhMi01Yjk4NmI2MjMyNTEiLCJhdXRoIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNjc1NDIzNDc1LCJleHAiOjE2NzYwMjgyNzV9.4qh-SmjZ4yR69dGCU_V5PSUZZQ-2S70Wr0DunxhKVVsihh8gbk2X3GOmZ3ld46j7IvufX8bfM2ee7xtzeJg-dg
userId: 159b49cd-78d2-4b2d-8aa2-5b986b623251

{
  "body": "koseRoomName",
  "searchType": "WAITROOMNAME"
}

> {%
    client.test("waitRoom 검색 조건에 따라 waitRoom 리스트 반환", function() {
        client.assert(response.status === 200, "Response status is OK");
    });
%}

### 2. waitRoom 검색 (slice)
GET {{baseUrl}}/waitroom-slice/search
Content-Type: application/json
Accept: */*
Connection: keep-alive
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNTliNDljZC03OGQyLTRiMmQtOGFhMi01Yjk4NmI2MjMyNTEiLCJhdXRoIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNjc1NDIzNDc1LCJleHAiOjE2NzU0NDUwNzV9.H9mLnrDz2qtRkw3eZdUrFaZZJvMIbaqxmFkXh8Z3sYT6cVUXglaO0AUIw-JHSxiyBa6mhJDtJh_wnmiW-HAkfA
RefreshToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNTliNDljZC03OGQyLTRiMmQtOGFhMi01Yjk4NmI2MjMyNTEiLCJhdXRoIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNjc1NDIzNDc1LCJleHAiOjE2NzYwMjgyNzV9.4qh-SmjZ4yR69dGCU_V5PSUZZQ-2S70Wr0DunxhKVVsihh8gbk2X3GOmZ3ld46j7IvufX8bfM2ee7xtzeJg-dg
userId: 159b49cd-78d2-4b2d-8aa2-5b986b623251

{
  "body": "koseRoomName",
  "searchType": "WAITROOMNAME",
  "page": 0,
  "limit": 10
}

> {%
    client.test("waitRoom 검색 조건에 따라 waitRoom pageable 반환", function() {
        client.assert(response.status === 200, "Response status is OK");
    });
%}