spring:
  application:
    name: wait-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  profiles:
    include:
      - db
      - aspect
      - cloud
      - oauth
      - kafka

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh